### ISSUE TITLE
Add a Point Source Tutorial

### ISSUE THREAD

**Issue by pierromond** [Universite-Gustave-Eiffel/NoiseModelling#137]
Add a Point Source Tutorial as NoiseModelling v2.0

**Comment by nicolas-f** [comment]
Maybe something similar as the industrial sound sources tutorial:

https://github.com/Ifsttar/NoiseModelling/blob/master/wiki/04-Industrial-sound-sources-application.md

**Comment by whywayne2020** [comment]
This will help to calcuate industry plant noise and building equipment noise.

**Comment by pierromond** [comment]
We did it !

**Comment by jonnor** [comment]
The documentation and the results look great!
