### ISSUE TITLE
Hourly average light vehicle count in double type ?

### ISSUE THREAD

**Issue by ebocher** [Universite-Gustave-Eiffel/NoiseModelling#343]
Here https://github.com/Ifsttar/NoiseModelling/blob/cnossos/wps_scripts/src/main/groovy/org/noise_planet/noisemodelling/wps/NoiseModelling/Noise_level_from_traffic.groovy#L67 the hourly average light vehicle count is expressed as double.  
Shouldn't it be in integer ?

**Comment by pierromond** [comment]
Yes it should.

**Comment by nicolas-f** [comment]
Its the result of an average as it is computed from Day Evening and Night periods. You can put integer column if you want it will still work.
