### ISSUE TITLE
wall absorption coefficient not affecting the results

### ISSUE THREAD

**Issue by thinklikeanarchitect** [Universite-Gustave-Eiffel/NoiseModelling#499]
I have just started to use Noise Modelling 4.0 software. It is really easy to use and very fast. I have just had an issue with "wall absorption coefficient" which is an optional field in the wps block of “noise emissions from traffic”. The absorption value does not affect the resulting noise maps. I have tried different values between 0 and 1, but nothing changed. I am trying to see the effect of a noise barrier and therefore this coefficient is very important. By the way, I have drawn noise barrier as a polygon, because only line does not considered by the software even if I have given it a height. I have tried to change the thickness of the barrier, but nothing changed even after.

Last, it may be a feature request that there should be a different field except from the “buildings” for the noise barriers. Otherwise you have to use the same coefficient for buildings and noise barriers, because you need the merge both geometries to use as “buildings”.

Could you please help me with this?

**Comment by gpetit** [comment]
Hi @thinklikeanarchitect and thanks for your message.
We were not aware of the problem you are facing.
In order to try to help you, would you have more elements to send us (data, logs, ...)?

**Comment by thinklikeanarchitect** [comment]
Hi,

The corresponding "buildings, roads, lw_roads and receiver" files are in the attachment. Moreover, I have changed wall absorption coefficent from 0.1 to 0.9 correspondingly (map and map2 files), however resulting contour maps are exactly same. You can reproduce the same with the attached files.

[wps_builder_file.txt](https://github.com/Universite-Gustave-Eiffel/NoiseModelling/files/9409858/wps_builder_file.txt)

[CONFIG.zip](https://github.com/Universite-Gustave-Eiffel/NoiseModelling/files/9409842/CONFIG.zip)
.

**Comment by gpetit** [comment]
Thanks, we will have a look

**Comment by thinklikeanarchitect** [comment]
Thank you, by the way, I have created a simple tutorial video for beginners: https://youtu.be/DvIT9zX4S3w

**Comment by thinklikeanarchitect** [comment]
Hi,

Have you ever had a chance to look at the issue?

**Comment by nicolas-f** [comment]
Hi,

We have cnossos unit test that is checking wall absorption and there is no issue. Maybe if you provide your test case ?

**Comment by nicolas-f** [comment]
Sorry didn't see the attached files. We will test it when we will have the time and give you a feedback here.

best regards

**Comment by thinklikeanarchitect** [comment]
Thank you.

**Comment by thinklikeanarchitect** [comment]
I have missed the NM days, unfortunately, but I am preparing an article using NM and let you know when it is published. Thank you for your support.

**Comment by pierromond** [comment]
You can still join us today if you want ! Just send us your e-mail (contact @ noise-planet.org) to receive the invitation link.

**Comment by nicolas-f** [comment]
I've looked into it. The sound source is in collision with the wall, you should offset the sound source a little from the wall.

![image](https://user-images.githubusercontent.com/1382241/191206641-f24d2fa0-0f62-487c-8db1-008d0c540bd7.png)

There is very little difference because for this receiver the main contribution is direct sound field (not visible in iso contours)

**Comment by nicolas-f** [comment]
resolved
