### ISSUE TITLE
Process failed during execution

### ISSUE THREAD

**Issue by IsotoCedex** [Universite-Gustave-Eiffel/NoiseModelling#516]
If you ignore this issue template, we may not be able to answer your issue.

**NoiseModelling version**
NoiseModelling 4.0.1

**Describe the bug**
Trying to copute a large surface model with own tables, created by GIS.
Have imported tables BUILDINGS, ROADS, RECEIVERS and DEM
Have created in Nosie Modelling - LW_ROADS
PK of all tables are OK.
Ran NOISE FROM SOURCE (with LW_ROADS) and NOISE FROM TRAFFIC (with ROADS)
Both fail.

** Error un Noise Modelling WSP**
Process failed during execution javax.script.ScriptException: java.lang.IllegalArgumentException: 
Invalid ordinate index: 2 java.lang.IllegalArgumentException: Invalid ordinate index: 2 Invalid 
ordinate index: 2

**Geoserver log**

Request: execute
    service = WPS
    version = 1.0.0
    baseUrl = http://localhost:9580/geoserver/
    identifier:
        value = NoiseModelling:Noise_level_from_traffic
    dataInputs:
        input[0]:
            identifier = net.opengis.ows11.impl.CodeTypeImpl@7a15e21f (value: 
confSkipLevening, codeSpace: null)
            data = net.opengis.wps10.impl.DataTypeImpl@6e13a69einput[0]:
            identifier = net.opengis.ows11.impl.CodeTypeImpl@23a099f6 (value: tableReceivers, codeSpace: null)
            data = net.opengis.wps10.impl.DataTypeImpl@1cafe94dinput[0]:
            identifier = net.opengis.ows11.impl.CodeTypeImpl@49fff5dd (value: tableBuilding, codeSpace: null)
            data = net.opengis.wps10.impl.DataTypeImpl@3a2b8d2ainput[0]:
            identifier = net.opengis.ows11.impl.CodeTypeImpl@1de3dcb0 (value: confSkipLday, codeSpace: null)
            data = net.opengis.wps10.impl.DataTypeImpl@7e65bbc0input[0]:
            identifier = net.opengis.ows11.impl.CodeTypeImpl@4882f8cc (value: confSkipLnight, codeSpace: null)
            data = net.opengis.wps10.impl.DataTypeImpl@2e267e2binput[0]:
            identifier = net.opengis.ows11.impl.CodeTypeImpl@2d232103 (value: tableDEM, codeSpace: null)
            data = net.opengis.wps10.impl.DataTypeImpl@7ecb24dcinput[0]:
            identifier = net.opengis.ows11.impl.CodeTypeImpl@2150f751 (value: tableRoads, codeSpace: null)
            data = net.opengis.wps10.impl.DataTypeImpl@3c9a1276
    responseForm:
        rawDataOutput:
            identifier = net.opengis.ows11.impl.CodeTypeImpl@88517df (value: result, 
codeSpace: null)

**Comment by nicolas-f** [comment]
Hi,
Can you post here as a file the Receivers table in the GEOJSON format ?
thanks

**Comment by IsotoCedex** [comment]
Hi again,

It is solved. The problem was the absence of Z value in receivers table. I realized thanks to your request.

Thanks so much!!


Un saludo.

Ignacio Soto Molina
Contratado I+D+i del Área de Ruido Ambiental
Centro de Estudios de Técnicas Aplicadas (CETA)

Tel. 91 335 72 68
Ext. 7268
Email: ***@***.******@***.***>

***@***.***

De: nicolas-f ***@***.***>
Enviado el: lunes, 26 de septiembre de 2022 12:48
Para: Universite-Gustave-Eiffel/NoiseModelling ***@***.***>
CC: Ignacio Soto Molina ***@***.***>; Author ***@***.***>
Asunto: Re: [Universite-Gustave-Eiffel/NoiseModelling] Process failed during execution (Issue #516)


Hi,
Can you post here as a file the Receivers table in the GEOJSON format ?
thanks

**Comment by nicolas-f** [comment]
nice! best regards

**Comment by IsotoCedex** [comment]
Hi, of course.

{
"type": "FeatureCollection",
"name": "Receivers_SPA",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::25830" } },
"features": [
{ "type": "Feature", "properties": { "PK": 1 }, "geometry": { "type": "Point", "coordinates": [ 242679.809700000099838, 4648795.3728 ] } },
{ "type": "Feature", "properties": { "PK": 2 }, "geometry": { "type": "Point", "coordinates": [ 341754.977300000376999, 4192151.466900000348687 ] } },
{ "type": "Feature", "properties": { "PK": 3 }, "geometry": { "type": "Point", "coordinates": [ 305959.486800000071526, 4533058.568 ] } },
{ "type": "Feature", "properties": { "PK": 4 }, "geometry": { "type": "Point", "coordinates": [ 637672.77419999986887, 4251825.703199999406934 ] } },
{ "type": "Feature", "properties": { "PK": 5 }, "geometry": { "type": "Point", "coordinates": [ 496666.146399999968708, 4600554.84940000064671 ] } },
{ "type": "Feature", "properties": { "PK": 6 }, "geometry": { "type": "Point", "coordinates": [ 708005.044400000013411, 4409949.567500000819564 ] } },
{ "type": "Feature", "properties": { "PK": 7 }, "geometry": { "type": "Point", "coordinates": [ 707932.944099999964237, 4304262.157199999317527 ] } },
{ "type": "Feature", "properties": { "PK": 8 }, "geometry": { "type": "Point", "coordinates": [ 702422.259100000374019, 4620979.296499999240041 ] } },
{ "type": "Feature", "properties": { "PK": 9 }, "geometry": { "type": "Point", "coordinates": [ 580508.183500000275671, 4227307.945599999278784 ] } },
{ "type": "Feature", "properties": { "PK": 10 }, "geometry": { "type": "Point", "coordinates": [ 529409.482599999755621, 4513825.940700000151992 ] } },
{ "type": "Feature", "properties": { "PK": 11 }, "geometry": { "type": "Point", "coordinates": [ 741438.901600000448525, 4638186.031300000846386 ] } },
{ "type": "Feature", "properties": { "PK": 12 }, "geometry": { "type": "Point", "coordinates": [ 16398.041100000031292, 4781802.914100000634789 ] } },
{ "type": "Feature", "properties": { "PK": 13 }, "geometry": { "type": "Point", "coordinates": [ 514429.853400000371039, 4633547.343399999663234 ] } },
{ "type": "Feature", "properties": { "PK": 14 }, "geometry": { "type": "Point", "coordinates": [ 614625.747700000181794, 4489232.498800000175834 ] } },
{ "type": "Feature", "properties": { "PK": 15 }, "geometry": { "type": "Point", "coordinates": [ 577707.973199999891222, 4249070.67200000025332 ] } },
{ "type": "Feature", "properties": { "PK": 16 }, "geometry": { "type": "Point", "coordinates": [ 716952.326799999922514, 4253843.519500000402331 ] } },
{ "type": "Feature", "properties": { "PK": 17 }, "geometry": { "type": "Point", "coordinates": [ 666150.262799999676645, 4714686.975199999287724 ] } },
{ "type": "Feature", "properties": { "PK": 18 }, "geometry": { "type": "Point", "coordinates": [ 458701.315799999982119, 4264071.93720000050962 ] } },
{ "type": "Feature", "properties": { "PK": 19 }, "geometry": { "type": "Point", "coordinates": [ 437795.807300000451505, 4495861.814500000327826 ] } },
{ "type": "Feature", "properties": { "PK": 20 }, "geometry": { "type": "Point", "coordinates": [ 204168.210099999792874, 4391957.050499999895692 ] } },
{ "type": "Feature", "properties": { "PK": 21 }, "geometry": { "type": "Point", "coordinates": [ 57995.755099999718368, 4699027.968699999153614 ] } },
{ "type": "Feature", "properties": { "PK": 22 }, "geometry": { "type": "Point", "coordinates": [ 249391.071800000034273, 4761589.262199999764562 ] } },
{ "type": "Feature", "properties": { "PK": 23 }, "geometry": { "type": "Point", "coordinates": [ 196098.539300000295043, 4276557.472400000318885 ] } },
{ "type": "Feature", "properties": { "PK": 24 }, "geometry": { "type": "Point", "coordinates": [ 633240.647300000302494, 4388838.909700000658631 ] } },
{ "type": "Feature", "properties": { "PK": 25 }, "geometry": { "type": "Point", "coordinates": [ 242482.808899999596179, 4487935.917099999263883 ] } },
{ "type": "Feature", "properties": { "PK": 26 }, "geometry": { "type": "Point", "coordinates": [ 533574.935300000011921, 4506885.050599999725819 ] } },
{ "type": "Feature", "properties": { "PK": 27 }, "geometry": { "type": "Point", "coordinates": [ 377024.496600000187755, 4182000.569399999454618 ] } },
{ "type": "Feature", "properties": { "PK": 28 }, "geometry": { "type": "Point", "coordinates": [ 314296.217400000430644, 4222985.468900000676513 ] } },
{ "type": "Feature", "properties": { "PK": 29 }, "geometry": { "type": "Point", "coordinates": [ 177142.922600000165403, 4356907.270600000396371 ] } },
{ "type": "Feature", "properties": { "PK": 30 }, "geometry": { "type": "Point", "coordinates": [ 204972.276700000278652, 4317644.5483 ] } },
…..
{ "type": "Feature", "properties": { "PK": 2291131 }, "geometry": { "type": "Point", "coordinates": [ 290624.82909999974072, 4806742.2741 ] } },
{ "type": "Feature", "properties": { "PK": 2291132 }, "geometry": { "type": "Point", "coordinates": [ 290127.859699999913573, 4806960.49070000089705 ] } },
{ "type": "Feature", "properties": { "PK": 2291133 }, "geometry": { "type": "Point", "coordinates": [ 289666.628999999724329, 4807168.453099999576807 ] } },
{ "type": "Feature", "properties": { "PK": 2291134 }, "geometry": { "type": "Point", "coordinates": [ 289150.015800000168383, 4807249.910800000652671 ] } }
]
}

Un saludo.

Ignacio Soto Molina
Contratado I+D+i del Área de Ruido Ambiental
Centro de Estudios de Técnicas Aplicadas (CETA)

Tel. 91 335 72 68
Ext. 7268
Email: ***@***.******@***.***>

***@***.***

De: nicolas-f ***@***.***>
Enviado el: lunes, 26 de septiembre de 2022 12:48
Para: Universite-Gustave-Eiffel/NoiseModelling ***@***.***>
CC: Ignacio Soto Molina ***@***.***>; Author ***@***.***>
Asunto: Re: [Universite-Gustave-Eiffel/NoiseModelling] Process failed during execution (Issue #516)


Hi,
Can you post here as a file the Receivers table in the GEOJSON format ?
thanks
