### ISSUE TITLE
installation 

### ISSUE THREAD

**Issue by alexandre35jn** [Universite-Gustave-Eiffel/NoiseModelling#525]
Hello, I have a problem with installing noise modeling, when I go in the WPS builder interface . I have the wrong main menu to the right of the interface.
![Capture](https://user-images.githubusercontent.com/104896134/198061555-0ee8c928-1dc1-4f09-a6d7-a80e520ba8f9.PNG)

**Comment by gpetit** [comment]
Hi @alexandre35jn and sorry for this problem (first time I see this!).

Can you tell us what version of NoiseModelling you are using and what format the installer is in (.exe, .sh, ... )?

It seems you are using Opera. Have you tried with an another web browser ?

**Comment by nicolas-f** [comment]
I think you used start.jar instead of NoiseModelling_xxx\bin\startup_windows.bat

Please read the documentation and follow the tutorials:

https://noisemodelling.readthedocs.io/

![image](https://user-images.githubusercontent.com/1382241/198207626-f0a56090-9696-4787-98c8-4961cc747a76.png)

**Comment by nicolas-f** [comment]
solved
