### ISSUE TITLE
Wrong G factor for water

### ISSUE THREAD

**Issue by gpetit** [Universite-Gustave-Eiffel/NoiseModelling#526]
https://github.com/Universite-Gustave-Eiffel/NoiseModelling/blob/e6f87cb57c508a777fb28b3e07ad2fd26fcb9ed7/wps_scripts/src/main/groovy/org/noise_planet/noisemodelling/wps/Import_and_Export/Import_OSM.groovy#L736

Is it correct ? I thought that for water, the G factor was equal to 0 (see [CNOSSOS-EU](https://hal.archives-ouvertes.fr/hal-00985998/document) page 86)

@nicolas-f @pierromond

**Comment by pierromond** [comment]
You are allright, G=0 seems to be a better choice !

**Comment by pierromond** [comment]
#576
