### ISSUE TITLE
Type error for input parameters as integers

### ISSUE THREAD

**Issue by GwnGuillaume** [Universite-Gustave-Eiffel/NoiseModelling#529]
**NoiseModelling version**
NoiseModelling 4.0.2 ( NoiseModelling_without_gui.zip)

**Describe the bug**
When running some scripts to generate a grid of receivers (as Random_Grid.groovy, see below, I get the message: ERROR org.noise_planet - Cannot cast object '100' with class 'java.lang.String' to class 'java.lang.Integer'. Modifying the corresponding instruction (*nReceivers = input['nReceivers']*) in the groovy script as *nReceivers = input['nReceivers'] as Integer* solves the issue.

**To Reproduce**
1. Run the command *./NoiseModelling_without_gui/bin/wps_scripts -w ./ -s NoiseModelling_without_gui/noisemodelling/wps/Receivers/Random_Grid.groovy -buildingTableName BUILDING -sourcesTableName ROAD_TRAFFIC -nReceivers 100* in a terminal

**Geoserver log**
No geoserver.log

**Comment by nicolas-f** [comment]
Thanks
