### ISSUE TITLE
Some issues when using command-line interface

### ISSUE THREAD

**Issue by jtagusari** [Universite-Gustave-Eiffel/NoiseModelling#531]
Hello, I am trying to use NoiseModelling with command-line interface (v 4.0.0) and found some problems. 
The platform I am using is Windows 10 / MinGW.

**1. NULL `inputs` field cannot be set**

Although `inputs = [ ]` is given in `get_started_tutorial.groovy` script, it throws an error, as follows:

```
[main] ERROR org.noise_planet - class java.util.ArrayList cannot be cast to class java.util.Map (java.util.ArrayList and java.util.Map are in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class java.util.Map (java.util.ArrayList and java.util.Map are in module java.base of loader 'bootstrap')
        at org.noisemodelling.runner.Main.main(Main.java:193)
``` 

Actually I do not know the critical reason why I got this error, but it is solved when I give non-NULL inputs such as

```
inputs = [
        runCalc: [
                name       : 'hoge',
                title      : 'hoge',
                description: 'hoge',
                type       : Boolean.class
        ]
]
```

Is there way to run a groovy script with NULL inputs variable?

**2. Argument must be given for groovy script**

It may be the spec, but at least an argument is necessary to execute groovy script.

For example, the following script cannot be executed.
```
./bin/wps_scripts -w ./ -s noisemodelling/wps/Database_Manager/Display_Database.groovy
```

The following is OK
```
./bin/wps_scripts -w ./ -s noisemodelling/wps/Database_Manager/Display_Database.groovy -showColumns true
```

Is there any way to run a groovy script without giving an argument?

**3. Boolean argument for groovy script is not valid**

For example, the `showColumns` argument is not set to false even using the following script
```
./bin/wps_scripts -w ./ -s noisemodelling/wps/Database_Manager/Display_Database.groovy -showColumns false
```

It would be because of the following expression in `Display_Database.groovy`, where boolean is defined by: `Boolean showColumnName = input['showColumns'] as Boolean`.

I think it should be replaced with `Boolean showColumnName = input['showColumns'].toBoolean()`, which provides `false` if the argument is not `"true"`.

I'm glad if you consider changing the script.

**Acknowledgement for the developers**

Although some errors remain, I think the open source software for calculating sound levels is very significant and a great experiment.
I would like thank the developers.

**Comment by nicolas-f** [comment]
Hi,

Thanks for your interest in NoiseModelling.

1. ```ArrayList cannot be cast to class java.util.Map``` 

This issue has been fixed, but not released. 

https://github.com/Universite-Gustave-Eiffel/NoiseModelling/commit/ef424b3ed3daf6fa6f2354025aef986c5787457a

2. 
3. 

According to your proposition I have updated the source code:

https://github.com/Universite-Gustave-Eiffel/NoiseModelling/commit/0b0d2a6f66f8140d058121e3e926bdcba71ddf98

Thanks
