### ISSUE TITLE
Receiver points at 0.1m from buildings

### ISSUE THREAD

**Issue by danigras** [Universite-Gustave-Eiffel/NoiseModelling#532]
Your software creates receiver points 2m from buildings.
I inform you that the DIRECTIVE (EU) 2021/1226 of 21 December 2020 foresees that the receptors are created at 0.1 m from the buildings and with the two alternative methods proposed on page 29.

Documentation:
English version 
https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32021L1226&from=IT

French version
https://eur-lex.europa.eu/legal-content/FR/TXT/PDF/?uri=CELEX:32021L1226&from=IT

**Comment by pierromond** [comment]
Dear @danigras, you can easily change this parameter directly in the WPS file. 
see : https://noisemodelling.readthedocs.io/en/latest/WPS_Blocks.html
or https://noisemodelling.readthedocs.io/en/latest/Own_Wps.html

I hope it can help you. In the future, we could put this parameter as a controllable parameter by the user.

Thank you for the comment.

**Comment by pierromond** [comment]
here you can find the fix : https://github.com/Universite-Gustave-Eiffel/NoiseModelling/pull/534 it will be included in the next version of NM.

Thanks @nicolas-f !
