### ISSUE TITLE
Does this work support to generate 3D result map?

### ISSUE THREAD

**Issue by mshmoon** [Universite-Gustave-Eiffel/NoiseModelling#533]
**Is your feature request related to a problem? Please describe.**
Does this work support to generate 3D result map?
May be,I think that 3D noise map is also important for users

**Comment by nicolas-f** [comment]
NoiseModelling is handling digital elevation model and buildings/walls are polygons that are extruded from this DEM ground. It is often described as a 2.5 D simulation.

**Comment by mshmoon** [comment]
> NoiseModelling is handling digital elevation model and buildings/walls are polygons that are extruded from this DEM ground. It is often described as a 2.5 D simulation.

I checked the document，I think if I change the receiver height, does the model will work well?

**Comment by mshmoon** [comment]
> NoiseModelling is handling digital elevation model and buildings/walls are polygons that are extruded from this DEM ground. It is often described as a 2.5 D simulation.

Sorry, I have  another question about source point. 
Why the source point will be place 2 meters from building facades.
Can I sample receiver point at  facades with 0 meter

**Comment by pierromond** [comment]
Yes, NoiseModelling can generate 3D receivers map. You have a WPS scripts called [Building_Grid3D.groovy] that does what you want.

2meters from facade is a criterium given by CNOSSOS to avoid that the first reflection on facade add 3dB to the sound level. 0 meter doesn't make sense, but you can put 0.000001m if you want, but take care about the reflections.

Kind regards.
