### ISSUE TITLE
To calculate road traffic noise with reference-type road surface

### ISSUE THREAD

**Issue by jtagusari** [Universite-Gustave-Eiffel/NoiseModelling#538]
Hello.

I'm using NoiseModelling CUI ver 4.0.

I would like to calculate the sound level with road pavement of dense asphalt concrete and would like to apply the reference condition in CNOSSOS-EU; however, an error is thrown when the "pvmt" attribute is set to "0" (0 is the identifier for the reference condition).
It would be great if you let me know how to set the reference pavement condition.

Thanks,

**Comment by nicolas-f** [comment]
Hi,

Supported road pavements are in this file (used by NoiseModelling emission code):

https://github.com/Universite-Gustave-Eiffel/NoiseModelling/blob/master/noisemodelling-emission/src/main/resources/org/noise_planet/noisemodelling/emission/coefficients_Road_Cnossos_2020.json

ex: "NL07"

**Comment by jtagusari** [comment]
Thank you very much!
