### ISSUE TITLE
3d Building Geometry

### ISSUE THREAD

**Issue by thinklikeanarchitect** [Universite-Gustave-Eiffel/NoiseModelling#546]
Hi,

I am using Qgis for preparing the geometry for the simulation. Only height parameter is available to define buildings. So the building geometry is just an extrusion of a footprint which is very very basic representation of any building. 

Is it possible to define complex building geometries? At least can we define a canopy/balcony at heigher levels then zero ground? Thank you for your understanding and patience.

**Comment by pierromond** [comment]
Yes, only extrusion are available in standard noise mapping methods (as CNOSSOS which is implemented in NM).

Maybe you should look tools as I-SIMPA, to take into account this kind of geometries...

**Comment by pierromond** [comment]
Duplicate https://github.com/Universite-Gustave-Eiffel/NoiseModelling/issues/547

**Comment by thinklikeanarchitect** [comment]
> Yes, only extrusion are available in standard noise mapping methods (as CNOSSOS which is implemented in NM).
> 
> Maybe you should look tools as I-SIMPA, to take into account this kind of geometries...

https://noisemodelling.readthedocs.io/en/latest/Input_buildings.html?highlight=z%20coordinate#table-definition

This helps me a lot. 'z object' definitely enough to define balcony,canopy and roof!

**Comment by zhengping97** [comment]
Sorry, can check if I'm understanding it correctly, does the z-coordinates given refers to the z ground, and based on the height the NoiseModeling will calculate the z-object?
