### ISSUE TITLE
3D buildings

### ISSUE THREAD

**Issue by zhengping97** [Universite-Gustave-Eiffel/NoiseModelling#547]
**NoiseModelling version**
4.0.2

**Describe the bug**
Hi, I would like to clarify how the z-coordinate of the 3D building works in the noise modeling tool. (https://noisemodelling.readthedocs.io/en/latest/Input_buildings.html?highlight=z%20coordinate#table-definition)

If the geojson coordinates imported includes the z-coordinate (e.g. [11550961.555405518,145315.2197543895,4] in EPSG3857) the z-coordinates will means my model will be elevated 4 meters off ground 0 right? Then if the z-coordinate is written as 0 will my buildings be calculated on the ground 0?

Trying to achieve the structure as shown below (generated in qgis):
![image](https://user-images.githubusercontent.com/36413759/222044308-d8b77339-07d7-42cb-bf21-50951cfaaba3.png)

where the 5 layers of circle polygon that represented the crown of the tree are at different z-coordinates. Tested buildings with and without z-coordinates but the results at the receivers doesn't change. Please advise, thank you.

**Comment by Nitnelav** [comment]
I am not sure how to technically achieve those geometries but I have to point out that trees should not be modeled that way.
Leaves and branches can be considered acoustically transparent and the impact of trunks is often neglected in most simulations.
You can evaluate the (very small) impact on vegetation on façade absorptions for exemple but not for "masking" purposes.

**Comment by Nitnelav** [comment]
if these are not trees but concrete blocks you can ignore my previous comment :)

**Comment by zhengping97** [comment]
Thanks for the comment! I actually want to understand if is it possible for the noise modeling tool to recognize that my building structure is off the ground (e.g. roof).

**Comment by Nitnelav** [comment]
I believe that everything is projected down to ground, so no I believe a floating roof can not exist

**Comment by zhengping97** [comment]
Understood, thank you so much!

**Comment by zhengping97** [comment]
Hi Noise Modelling Team, I am part of a research group from Singapore Nanyang Technological University. We are interested in using this software tool to analyze noise in an urban area. We are currently using the import_osm block in the WPS builder to generate buildings. However, we realized that buildings with complex shapes are recognized differently. For instance, the marina bay sands buildings, where the observatory deck was supposed to be at the top of the buildings:

<img width="267" alt="image" src="https://user-images.githubusercontent.com/36413759/223919215-d0475a11-be41-495c-b914-14866ca86056.png">

Buildings generated by Noise Modelling, visualized in QGIS: (observation deck projected down to ground)

<img width="288" alt="image" src="https://user-images.githubusercontent.com/36413759/223919445-a69ce7aa-b198-49c6-b836-9e24ab20ed5c.png">

From what I note from the documentation, Noise Modelling is able to analyze complex roof shapes:
(https://noisemodelling.readthedocs.io/en/latest/Input_buildings.html?highlight=z%20coordinate#table-definition)

<img width="548" alt="image" src="https://user-images.githubusercontent.com/36413759/223919668-03208c91-e03a-451a-a333-e0fd94ed1ed1.png">

We hope to get some advice on what type of information is required for Noise Modelling in order to detect complex shapes or if there are any other software applications that we can export the data from to import into Noise Modelling for better representations. Thank you!

**Comment by Nitnelav** [comment]
I believe this is the typical shape (a hole in a building, typically any ark building) that is not supported by the CNOSSOS model (and therefore in NoiseModelling).

I am not familiar enough with the variety of acoustic propagation models to recommend any other software but the Harmonoise model could be worth looking at. It is known to be better than CNOSSOS-EU in many aspects, but I'm not sure about this particular issue.

**Comment by zhengping97** [comment]
Ok, thank you!
