### ISSUE TITLE
Wrong  release number in the web browser

### ISSUE THREAD

**Issue by gpetit** [Universite-Gustave-Eiffel/NoiseModelling#551]
I'm using the last release: NM v4.0.3

When NM is launched, in the web browser, the app is called ``NoiseModelling 4.0.4``

![image](https://user-images.githubusercontent.com/1871248/223442573-1240b792-e8ea-479d-8977-bb5e0ddacabe.png)

The release number is wrong since it should be ``4.0.3``

**Comment by nicolas-f** [comment]
I updated the release to 4.0.4 as it is marked with this version in libraries
