### ISSUE TITLE
Receivers: building_grid- new opzion distance from wall don't work

### ISSUE THREAD

**Issue by danigras** [Universite-Gustave-Eiffel/NoiseModelling#552]
NoiseModelling version 4.0.4

Hi, I'm using version 4.0.4 and I find that the new option distance from wall (great upgtate!!!) parameter doesn't work correctly. 
Receptors are always created 2m from the wall.
Below is an image with a parameter set in Noise Moddeling at 0.1 m, the result is always 2m. Thanks a lot.

Daniele

![immagine](https://user-images.githubusercontent.com/121245600/223989991-f37fc8ef-f8d8-4858-9cef-9b4b4bb22944.png)

**Comment by nicolas-f** [comment]
Hi,

Thanks for the feedback.

Yes there is an issue in the source code.

You don't have to wait for the next release, you can fix it by editing the script in your installation:

Edit this file (the path depends how you install it)
C:\Program Files (x86)\NoiseModelling\NoiseModelling\data_dir\scripts\wps\Receivers\Building_Grid.groovy

![image](https://user-images.githubusercontent.com/1382241/224030752-3ae25f22-6b5b-4ae8-a26e-46766d20aa68.png)

replace h by distance like shown in the diff. You don't have to restart NoiseModelling.
