### ISSUE TITLE
Questions about Noise Modelling possibilities

### ISSUE THREAD

**Issue by AmandineHJ** [Universite-Gustave-Eiffel/NoiseModelling#562]
Hello everyone !

I have just begin using Noise Modelling in order to do research and tests for noise map. I have some questions about the possibilities of this tool, and how to apply it. I am using Noise Modelling version 4.0.4. 

I was wondering if it is possible to overlap noise sources ? For example : if I want to produce a noise map with the noise of the roads and two particular point that emit noise, is it possible to calculate the noise into the environment with these 3 types of sources at the same time ?  And if it is possible, how do I do that ?

I have another question. I have tried to change the type of receivers, and put a "regular grid" instead of "Delaunay grid", and then I tried to create isosurface. I couldn't create Isosurface because Noise Modelling was looking for the "TRIANGLES" table. So do I conclude that it is mandatory to use the "Delaunay Grid" when we want to create Isosurfaces ? Can I create isosurfaces or squares (like for example colored squares 5m x 5m) by linking the points to have a coloured visual rendered ?

I thank you in advance for your replies and have a nice day !

Amandine

<img width="957" alt="Capture _ 1" src="https://user-images.githubusercontent.com/129366571/228778091-8c12d568-25d1-4826-82be-dba7cf825839.png">
<img width="950" alt="Capture _ 2" src="https://user-images.githubusercontent.com/129366571/228778097-5fa9b763-f0f5-49b2-84b1-c4670b9c33b5.png">

**Comment by nicolas-f** [comment]
Hi,

After your feature request, I have added an option to generate Triangles in the RegularGrid WPS:

https://github.com/Universite-Gustave-Eiffel/NoiseModelling/pull/563

You can download the file https://github.com/Universite-Gustave-Eiffel/NoiseModelling/raw/326710fb9b0e68172fe644607a8342402b453716/wps_scripts/src/main/groovy/org/noise_planet/noisemodelling/wps/Receivers/Regular_Grid.groovy
and place it in the folder `data_dir/scripts/wps/Receivers/`

**Comment by AmandineHJ** [comment]
Hi,

Thank you very much for your reply. I have tried this new block by place the file into the good folder but it doesn't seems to work.  I have run the block "Regular Grid" with my arguments. It stopped running when deleting the receivers from the roads in the noise modelling window, and now it doesn't work anymore. You can see the error message in the picture, and I can't drop the table "TRIANGLES" anymore. It is frozen.

Furthermore, do you know more about my first question about overlap sources ?
Thank you in advance

<img width="952" alt="image" src="https://user-images.githubusercontent.com/129366571/228839438-affd3732-d2ee-4c5e-b8f7-ed2af5809e05.png">
