### ISSUE TITLE
Error message when generating LW_ROADS table

### ISSUE THREAD

**Issue by AmandineHJ** [Universite-Gustave-Eiffel/NoiseModelling#572]
Hello,

I am currently trying to generate a table for roads noise level but I have an error message from WPS Builder.
I have established the model and imported the files "abs_1km2" as GROUND, "bat_1km2" as BUILDINGS and "coupe_routes_1km2" as ROADS into Noise Modelling. I imported my DEM, and then I used the Regular_Grid block to generate my receivers. After that, I tried to use the block Road_Emission_from_Traffic in order to calculate the new table LW_ROADS. I have now this error message and I don't understand why. Could you help me please ? You can find attached my work files.

<img width="957" alt="image" src="https://user-images.githubusercontent.com/129366571/233383849-cfee1a33-8e80-4350-a0a5-4089d812f394.png">

[Limoges_essais_toute_petite_zone.zip](https://github.com/Universite-Gustave-Eiffel/NoiseModelling/files/11286865/Limoges_essais_toute_petite_zone.zip)

**Comment by nicolas-f** [comment]
Hi,

You discarded the entire issue template, at least attach the geoserver log located in **data_dir\logs\geoserver.log**

**Comment by AmandineHJ** [comment]
You can find attached the geoserver log. I'm using the version 4.0.4 of Noise Modelling.

Thank you in advance for your help!

[geoserver.log](https://github.com/Universite-Gustave-Eiffel/NoiseModelling/files/11287999/geoserver.log)

**Comment by nicolas-f** [comment]
I looked at your data, the column PVMT in your roads must be one of the following values:

NL01
DEF
FR_R2
NL02
NL03
NL04
NL05
NL06
NL07
NL08
NL09
NL10
NL11
NL12
NL13
NL14
FR1D
FR1N
FR2D
FR2N
FR3D
FR3N

You can look at the characteristics of the roads in this file:

https://github.com/Universite-Gustave-Eiffel/NoiseModelling/blob/4.X/noisemodelling-emission/src/main/resources/org/noise_planet/noisemodelling/emission/coefficients_Road_Cnossos_2020.json

best regards,

Nicolas F.

**Comment by AmandineHJ** [comment]
Hi,

Thank you for your reply, it works really better now !

Have a nice day
