### ISSUE TITLE
Error (due to coordinates?) in version 4.0.4

### ISSUE THREAD

**Issue by jtagusari** [Universite-Gustave-Eiffel/NoiseModelling#579]
Hello all.

I have an error in the latest version (v 4.0.4) of NoiseModeling without GUI.
There was no error in version 4.0.0, but the latest version throws one.

Since the error disappeared when the receiver (or road) coordinates were changed, I think it is due to the positions between receiver and road, but details remain unclear.

I would be glad if you could give me some advice.
Thank you.

**To Reproduce**
1. import geometries, as follows (source of the files are in the text below)
> bin\wps_scripts -w . -s noisemodelling\wps\Import_and_Export\Import_File.groovy -pathFile ROADEXT.geojson
> bin\wps_scripts -w . -s noisemodelling\wps\Import_and_Export\Import_File.groovy -pathFile BUILDINGEXT.geojson
> bin\wps_scripts -w . -s noisemodelling\wps\Import_and_Export\Import_File.groovy -pathFile RECEIVEREXT.geojson

2. try calculating sound levels
> bin\wps_scripts -w . -s noisemodelling\wps\NoiseModelling\Noise_level_from_traffic.groovy -tableRoads ROADEXT -tableBuilding BUILDINGEXT -tableReceivers RECEIVEREXT

3. then I got errors
[main] INFO org.noise_plan

> [main] INFO org.noise_planet.noisemodelling - Start : Noise level from Traffic
> [main] INFO org.noise_planet.noisemodelling - inputs {tableReceivers=RECEIVEREXT, tableBuilding=BUILDINGEXT, s=noisemodelling\wps\NoiseModelling\Noise_level_from_traffic.groovy, progressVisitor=org.noise_planet.noisemodelling.pathfinder.RootProgressVisitor@64b3b1ce, w=., tableRoads=ROADEXT}
> [main] INFO org.noise_planet.noisemodelling - Start calculation... 
> [main] INFO org.noise_planet.noisemodelling.jdbc.PointNoiseMap - Collect all receivers in order to localize populated cells
> [main] INFO org.noise_planet.noisemodelling - Compute... 0.000 % (1 receivers in this cell)
> [main] INFO org.noise_planet.noisemodelling.jdbc.PointNoiseMap - Begin processing of cell 1 / 1
> [main] INFO org.noise_planet.noisemodelling.jdbc.PointNoiseMap - This computation area contains 1 receivers 1 sound sources and 1 buildings
> java.lang.IllegalArgumentException: Invalid ordinate index: 2
> [Thread-1] INFO org.noise_planet.noisemodelling.jdbc.LDENPointNoiseMapFactory$TableWriter - Write done, apply primary keys
> [main] ERROR org.noise_planet - Invalid ordinate index: 2
> java.lang.IllegalArgumentException: Invalid ordinate index: 2
>         at org.locationtech.jts.geom.CoordinateXY.setOrdinate(CoordinateXY.java:131)
>         at org.noise_planet.noisemodelling.pathfinder.ComputeCnossosRays$AbsoluteCoordinateSequenceFilter.filter(ComputeCnossosRays.java:1819)
>         at org.locationtech.jts.geom.LineString.apply(LineString.java:252)
>         at org.noise_planet.noisemodelling.pathfinder.ComputeCnossosRays.makeSourceRelativeZToAbsolute(ComputeCnossosRays.java:1582)
>         at org.noise_planet.noisemodelling.jdbc.PointNoiseMap.evaluateCell(PointNoiseMap.java:289)
>         at org.noise_planet.noisemodelling.jdbc.PointNoiseMap$evaluateCell$5.call(Unknown Source)
>         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
>         at org.noise_planet.noisemodelling.wps.NoiseModelling.Noise_level_from_traffic$_exec_closure2.doCall(Noise_level_from_traffic.groovy:693)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
>         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
>         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
>         at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
>         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
>         at groovy.lang.Closure.call(Closure.java:411)
>         at groovy.lang.Closure.call(Closure.java:427)
>         at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2296)
>         at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2281)
>         at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2346)
>         at org.codehaus.groovy.runtime.dgm$189.invoke(Unknown Source)
>         at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:246)
>         at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:55)
>         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
>         at org.noise_planet.noisemodelling.wps.NoiseModelling.Noise_level_from_traffic.exec(Noise_level_from_traffic.groovy:690)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
>         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
>         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
>         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
>         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
>         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:821)
>         at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:44)
>         at groovy.lang.Script.invokeMethod(Script.java:80)
>         at org.noisemode

**Source of the Geometries**

***Road***
{
"type": "FeatureCollection",
"name": "ROADEXT",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::32654" } },
"features": [
{ "type": "Feature", "properties": { "fid": 79, "PK": 79, "lv_d": 336.1, "lv_e": 47.4, "lv_n": 14.6, "mv_d": null, "mv_e": null, "mv_n": null, "hv_d": 37.7, "hv_e": 3.1, "hv_n": 4.6, "lv_spd_d": 60.0, "lv_spd_e": 60.0, "lv_spd_n": 60.0, "mv_spd_d": 60.0, "mv_spd_e": 60.0, "mv_spd_n": 60.0, "hv_spd_d": 60.0, "hv_spd_e": 60.0, "hv_spd_n": 60.0, "pvmt": "DEF", "temp_d": null, "temp_e": null, "temp_n": null, "ts_stud": null, "pm_stud": null, "junc_dist": null, "slope": null, "way": null, "tv_d": 336.1, "tv_e": 47, "tv_n": 15 }, "geometry": { "type": "LineString", "coordinates": [ [ 513590.729014362033922, 4757801.887386024929583 ], [ 513595.901971943443641, 4757802.172267452813685 ], [ 513674.110399187542498, 4757806.609313077293336 ] ] } }
]
}

***Building***
{
"type": "FeatureCollection",
"name": "BUILDINGEXT",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::32654" } },
"features": [
{ "type": "Feature", "properties": { "fid": 120, "PK": 120, "height": 6.0 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 513585.777394607895985, 4757820.490626117214561 ], [ 513587.964363642793614, 4757820.60392786655575 ], [ 513588.191723097697832, 4757816.245715986937284 ], [ 513576.053917663870379, 4757815.676830698736012 ], [ 513575.711379360407591, 4757822.97691108006984 ], [ 513585.6622037900961, 4757823.432493545114994 ], [ 513585.777394607895985, 4757820.490626117214561 ] ] ] } }
]
}

***Receiver***
{
"type": "FeatureCollection",
"name": "RECEIVEREXT",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::32654" } },
"features": [
{ "type": "Feature", "properties": { "PK": 1 }, "geometry": { "type": "Point", "coordinates": [ 513583.774412043334451, 4757814.036486100405455, 0.0] } }
]
}

[features.zip](https://github.com/Universite-Gustave-Eiffel/NoiseModelling/files/11451737/features.zip)

**Comment by nicolas-f** [comment]
Hi,

Not related to the issue but you should place the receiver using height > 0m .
![image](https://github.com/Universite-Gustave-Eiffel/NoiseModelling/assets/1382241/080514e8-1a70-4767-9a13-290320ee42d9) _cnossos-eu_

Did you try to set a Z coordinate to roads ? It is the height (relative to the specified digital elevation model) of the road. I think to noise emission will add 0.05m to the height as the position of the sound source.

**Comment by jtagusari** [comment]
Thank you @nicolas-f .

Setting Z value for receivers does not always solve the problem, but by setting Z values for roads, the error no longer appears, while I don't confirm that no errors appear in any settings. It would be nice to find out if the real cause of the error is in the road coordinate settings or if there are still other causes.

For setting the height of the sound sources to be 0.05 m, which Z values should I set, 0.00 m (0.05 m will be automatically added) or 0.05 m?
