### ISSUE TITLE
Question about a comparison with CADNAA

### ISSUE THREAD

**Issue by AmandineHJ** [Universite-Gustave-Eiffel/NoiseModelling#582]
Hi ! 

**NoiseModelling version**
I'm using NoiseModelling 4.0.4.

**Describe the bug**
I am trying to compare CADNAA and NoiseModelling results. I am working on a small file with only one road and one building and the results seems to be different with the same calculation mode (CNOSSOS EU). There is a difference about 6 dB(A) almost everywhere as you can see in the pictures : 

<img width="378" alt="image" src="https://github.com/Universite-Gustave-Eiffel/NoiseModelling/assets/129366571/27d90194-1896-40d2-819a-4fd2a1c1cad4">
Results from CADNAA

<img width="422" alt="image" src="https://github.com/Universite-Gustave-Eiffel/NoiseModelling/assets/129366571/5f9543e1-5614-4ecf-9ba1-ca3c0dc9cdf8">
Results from NoiseModelling

<img width="410" alt="image" src="https://github.com/Universite-Gustave-Eiffel/NoiseModelling/assets/129366571/77354ede-4998-4bc5-bb50-2ceb2acba7ec">
Comparison of the results

**Geoserver log**
[geoserver.log](https://github.com/Universite-Gustave-Eiffel/NoiseModelling/files/11531275/geoserver.log)

Do you have any idea why there is a such difference ? I have did research but I don't find why I have this difference. Maybe I did something wrong in my NoiseModelling parameters ? The two models have the same parameters (including maximum source-receiver distance).

Thank you for you reply,
Best Regards,
Amandine

**Comment by pierromond** [comment]
Hi Amandine, 

It seems that your emission noise levels are not the same. Are you sure to use the same kind of pavement, slope, the same cnossos model (2015 or 2019 update), etc. ?

**Comment by AmandineHJ** [comment]
Hello,

I tried to find what was the different betwenn my two models and it seems that it was not the same pavement. The one for NoiseModelling results was NL-08 and the one used into CADNAA was the reference pavement, that explains my issue.

It is better now, thank you very much.
Sincerely,
Amandine
