### ISSUE TITLE
Building3D_Grid not working

### ISSUE THREAD

**Issue by AmandineHJ** [Universite-Gustave-Eiffel/NoiseModelling#586]
Hi !

**NoiseModelling version**
NoiseModelling 4.0.4

**Describe the bug**
I am trying to calculate the block "Building3D_GRID" but I always have this error message :

<img width="955" alt="image" src="https://github.com/Universite-Gustave-Eiffel/NoiseModelling/assets/129366571/c4c2ed65-7c2c-43fe-b8eb-bbce7bcf5b5d">

I have tried to replace the Buiding3D_grid groovy file by the new one that has been created 3 month ago by you but it didn't change anything.

Furthermore, it doesn't create a RECEIVERS table as expected, but it is creating other tables : 

<img width="955" alt="image" src="https://github.com/Universite-Gustave-Eiffel/NoiseModelling/assets/129366571/93312402-0dfa-453c-8cee-6e81c2b8af81">

I really don't know what to do more. 
The Buiding_grid (without 3D) is working good.

**Geoserver log**
[geoserver.log](https://github.com/Universite-Gustave-Eiffel/NoiseModelling/files/11673419/geoserver.log)

Thank you in advance,
Amandine

**Comment by nicolas-f** [comment]
Hi,

This issue has been fixed and will be released in the next version.

You can wait for the next release or download the new script here and replace your existing script in `data_dir/scripts/wps/Receivers/` with the following file:

https://github.com/Universite-Gustave-Eiffel/NoiseModelling/blob/4.X/wps_scripts/src/main/groovy/org/noise_planet/noisemodelling/wps/Receivers/Building_Grid3D.groovy

**Comment by AmandineHJ** [comment]
Hi ! Thank you very much. I have downloaded the new script and now it work well. 
Have a nice day,
Sincerely,
Amandine
