### ISSUE TITLE
Invalid ordinate index

### ISSUE THREAD

**Issue by Y-Yahyaoui** [Universite-Gustave-Eiffel/NoiseModelling#588]
**NoiseModelling 4.0.2**

I imported 3 shapefiles (roads, buildings and receivers),
When I use the table_visualisation_data it works just fine
But when I use the table_visualisation_map I get this error :

> Process failed during execution javax.script.ScriptException: org.h2.jdbc.JdbcSQLNonTransientException: Exception calling user-defined function: "ST_Transform(conn1037456: url=jdbc:default:connection user=, MULTILINESTRING ((-219315.73490158713 312613.2367809003, -219315.58694700472 312613.1197399353)), 4326): No transformation found from epsg:32198 to epsg:4326"; SQL statement: select ST_ACCUM(ST_TRANSFORM(THE_GEOM ,4326)) THE_GEOM from ROADS [90105-214] org.h2.jdbc.JdbcSQLNonTransientException: Exception calling user-defined function: "ST_Transform(conn1037456: url=jdbc:default:connection user=, MULTILINESTRING ((-219315.73490158713 312613.2367809003, -219315.58694700472 312613.1197399353)), 4326): No transformation found from epsg:32198 to epsg:4326"; SQL statement: select ST_ACCUM(ST_TRANSFORM(THE_GEOM ,4326)) THE_GEOM from ROADS [90105-214] Exception calling user-defined function: "ST_Transform(conn1037456: url=jdbc:default:connection user=, MULTILINESTRING ((-219315.73490158713 312613.2367809003, -219315.58694700472 312613.1197399353)), 4326): No transformation found from epsg:32198 to epsg:4326"; SQL statement: select ST_ACCUM(ST_TRANSFORM(THE_GEOM ,4326)) THE_GEOM from ROADS [90105-214] No transformation found from epsg:32198 to epsg:4326

And then when I ran Noise_level_from_traffic I got this error : 

> Process failed during execution javax.script.ScriptException: java.lang.IllegalArgumentException: Invalid ordinate index: 2 java.lang.IllegalArgumentException: Invalid ordinate index: 2 Invalid ordinate index: 2

**Comment by Y-Yahyaoui** [comment]
I changed the data to the epsg 32619, now the map visualisation works, but the the noise_level_from_traffic still gives the same error

**Comment by Y-Yahyaoui** [comment]
Apparently the issue was that the files geometries was in 2D and not 3D

**Comment by LontongBalado** [comment]
> Apparently the issue was that the files geometries was in 2D and not 3D

Hello, Can you teach me how to do it ? I got same error in my Noise Modelling
