### ISSUE TITLE
Mixed map results and usage questions

### ISSUE THREAD

**Issue by romanian-bag-void** [Universite-Gustave-Eiffel/NoiseModelling#594]
**NoiseModelling version**
4.0

**Describe the bug**
Mixing railway and road traffic noise into 1 single map did not result in the desired output. Asking this since the documentation left me a bit puzzled.

**To Reproduce**
Do all steps in the [docs](https://noisemodelling.readthedocs.io/en/latest/Noise_Map_From_OSM_Tutorial.html) from step 1 to step 7 with the following mentions:
- At step 1, I noticed there were crashes with importing the entire region I wanted (București-Ilfov in Romania), so I downloaded 2 files, and imported each sequentially via `Import_OSM` in order for the program to not crash. I assume this happens because of the size (over 9mb) of the PBF files, and went ahead with it. When I checked the DB via dBeaver for the data, it seemed like they were properly imported and acted like everything worked together just fine, without any duplicates. I assume that the import task erases all previous data and that skipped over my head?
- At step 4, besides the traffic data generated via `Road_Emission_from_Traffic`, I also generated the rail data via `Railway_Emission_from_Traffic` task.
- At step 5 I used the `Noise_level_from_source` task twice, once for the before-generated `LW_ROADS` and once for `LW_RAILWAY`
- I continued with steps 6 and 7 as one would normally do.

The only mention I have is that I used the French railway train data for testing purposes. Please ignore the idea that I'm using French train data on Romanian railways. On one part, the Romanian Railways is beyond opaque with regards to what should be open-source data, on the other...I am fairly certain it does not know either how many trains of what kind it has. And how they function.

**Geoserver log**

Sadly the only place where log errors would've been relevant is the data import one, which I no longer have.

**Expected behavior**
A noise map of both rail and road traffic would be generated.

**Additional context**
I want to know the following:
- If I want to generate the data, I suppose I have to create 2 different maps (railway noise and road noise), is that correct?
- If I want to create 1 mega-table from both PBF files' data, I assume I have to create some temporary tables from the imported data of the first import, drop the first import tables, then re-do a import task and then merge the temporary tables with the new import tables, is that correct?

Many thanks in advance for any kind of help. :)

**Comment by pierromond** [comment]
> At step 1, I noticed there were crashes with importing the entire region I wanted (București-Ilfov in Romania), so I downloaded 2 files, and imported each sequentially via Import_OSM in order for the program to not crash. I assume this happens because of the size (over 9mb) of the PBF files, and went ahead with it. When I checked the DB via dBeaver for the data, it seemed like they were properly imported and acted like everything worked together just fine, without any duplicates. I assume that the import task erases all previous data and that skipped over my head?
> If I want to create 1 mega-table from both PBF files' data, I assume I have to create some temporary tables from the imported data of the first import, drop the first import tables, then re-do a import task and then merge the temporary tables with the new import tables, is that correct?

Yes, you will probably need some data manipulation In dBeaver. Maybe Romania also have some public data about the Buildings ? it is probably a better source of data if it exists. In fact, our script Import_OSM is a little bit "weak", you can also try to use geoclimate (https://github.com/orbisgis/geoclimate/tree/master/osm) tool to import OSM data ! It is a better tool. We would like to couple both tool in the near future.

So, finally, if you want to import OSM data, you can still use our tool but with all the limitations it has, but you can also try to find other tools or data on the net that could be better and easier to control, in fact, you need a BUILDINGS table which basically is a POLYGON Table with "Height". You could still use our script to import ground properties for example, it should better work for all Romania if you check the box "not calculate buildings".

> If I want to generate the data, I suppose I have to create 2 different maps (railway noise and road noise), is that correct?
Yes, and then merge them adding the energetic value on each receiver if it makes sense to your case.

**Comment by romanian-bag-void** [comment]
Many thanks for the reply! I'll go for the simple temporary tables hack for both issues.

> Maybe Romania also have some public data about the Buildings ? [...] You could still use our script to import ground properties for example, it should better work for all Romania if you check the box "not calculate buildings".

Sadly not. I guess I'll just tick "not calculate buildings". Maybe I'll get to find some building data at some point, but I haven't seen any around at all.

Other than that, I think this question can be closed.

**Comment by romanian-bag-void** [comment]
Another usage question: I managed compiling the project for Postgres after I realized late that perhaps Postgres/PostGIS might offer better performance than H2 Embedded GIS.

I cloned the project. I managed to modify the files mentioned [here](https://noisemodelling.readthedocs.io/en/latest/NoiseModellingOnPostGIS.html?highlight=postgis#introduction), ran the WPS build scripts in `\wps_scripts` and used the generated code in `build\install\scriptrunner`, yet sadly it went forward with creating a H2 DB.

Did anything change ever since the documentation page was added? Am I missing anything?

Many thanks in advance for any kind of help. :)

**Comment by pierromond** [comment]
Hi, 

Did you manage to include this in your main file ?    
        DataSourceFactoryImpl dataSourceFactory = new DataSourceFactoryImpl();
        Properties p = new Properties();
        p.setProperty("serverName", "localhost");
        p.setProperty("portNumber", "5432");
        p.setProperty("databaseName", "postgres");
        p.setProperty("user", "postgres");
        p.setProperty("password", "");
      

Using PostGIS with NoiseModelling is not well maintained... I can only say that two years ago it was working. In some case it is true that postGIS is a little bit faster, but if speed is your only requirement to use postGIS, I think that maybe it is a lot of work for little gains. By the way, if you succeed in doing it, we will be very happy to hear about your result. Maybe we can create a special feed on it ! Give us more detail, and maybe we can help you.
