### ISSUE TITLE
Regular_Grid.groovy not working without GUI

### ISSUE THREAD

**Issue by mspitzna** [Universite-Gustave-Eiffel/NoiseModelling#597]
**NoiseModelling version**
Version 4.0.4 without GUI

**Describe the bug**
The Regular_Grid.groovy script throws a NullPointerException without any clear error message. I can run any .groovy-script via the terminal. All the other scripts I'm using work with the following command:

`./bin/wps_scripts "-w" "./" "-s" "./noisemodelling/wps/Receivers/Delaunay_Grid.groovy"`

I got a running pipeline that imports OSM Files and generates the grid via Delaunay_Grid.groovy, etc. In my case, the General_Grid is the most fitting one, but exchanging the scripts won't work. I thought its some data issue, but the script won't even run without any arguments. All the other scripts return the expected arguments. 

Here is the output of the script:
```
calling: ./bin/wps_scripts "-w" "./" "-s" "./noisemodelling/wps/Receivers/Regular_Grid.groovy"

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/F:/EigeneDateien/Dokumente/AI_Docs/PhD/pipeline/NoiseModelling_without_gui/lib/groovy-2.5.5.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

[main] ERROR org.noise_planet - null
java.lang.NullPointerException
        at org.noisemodelling.runner.Main.lambda$main$0(Main.java:196)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at org.noisemodelling.runner.Main.main(Main.java:193)
```

I reproduced the pipeline in the GUI version 4.0.4 and it worked perfectly with the Delaunay- and general-grid. Redownloading the NoiseModelling-package didn't fix anything. %JAVA_HOME% points to the JDK-11.0.1. 

I'm not sure why it works with the GUI but not via script. Might this be a Java issue?

**To Reproduce**
1. Download NoiseModelling without GUI version 4.0.4
2. Call the script Receivers:Regular_Grid.groovy via terminal

**Expected behavior**
It should output the expected arguments for the script.

Thanks for your help!

**Comment by nicolas-f** [comment]
Hi,

Thanks for your interest in NoiseModelling.

It seems it works with nightly version, you can try it out here:

https://github.com/Universite-Gustave-Eiffel/NoiseModelling/suites/14543566157/artifacts/823036124

**Comment by mspitzna** [comment]
Hey nicolas-f, with this specific version, it worked perfectly. Thanks for your help!
