### ISSUE TITLE
NoiseModelling4.0.5.exe does not run properly

### ISSUE THREAD

**Issue by IsotoCedex** [Universite-Gustave-Eiffel/NoiseModelling#610]
**NoiseModelling version**
4.0.5

**Describe the bug**
I have installed NoiseModelling 4.0.5.
I also had version 4.0.4 installed (incorrectly referred as 4.0.3.)
Running NM 4.0.5 (NoiseModelling.exe) starts version 4.0.4 (misreferred as 4.0.3.)
I have renamed the folder C:\...\Programs\NoiseModelling\NoiseModelling_4.0.5 as C:\...\Programs\NoiseModelling\NoiseModelling_4.0.3

Now it does start, but I don't know the implications it may have on the execution of the modules.

**Screenshots**
This is version 4.0.5., misreferred as 4.0.4, launched from folder C:\...\Programs\NoiseModelling\NoiseModelling_4.0.3     :)

![image](https://github.com/Universite-Gustave-Eiffel/NoiseModelling/assets/87642224/bf019c4d-3d98-4dbb-b350-16f712906779)

**Comment by Nitnelav** [comment]
Mmm that's odd.
In your Local/Programs/Noisemodelling folder, the exe's date is 21/02/2023 wich would indicate that the installer didn't replace it on the 12/09/2023 install.
I quickly checked and there is no typo error in the install creation script (https://github.com/Nitnelav/NoiseModelling-installer/blob/a770c75a40d1c47497a05b87b3ade29c2a37df52/create_exe.au3#L9).
I will perform further tests, in the meantime could you uninstall an reinstall NoiseModelling ?

**Comment by IsotoCedex** [comment]
I just installed it, on another computer.
Files from version 4.0.4 (misreferred as 4.0.3) are those with an underscore (_).
The new ones, from the todays installation of NM 4.0.5, are the ones that I have marked with a black box.
Indeed, the executable file (NoiseModelling.exe) is created with the same date as version 4.0.4.

![image](https://github.com/Universite-Gustave-Eiffel/NoiseModelling/assets/87642224/bb12c299-60b3-4e83-bac0-0d270f791df1)

Note that the date of my previous installation is 08/22/2023, and that of the new installation is 09/13/2023. However, both .exe files have the same date, which does not match either of them (02/21/2023)

**Comment by Nitnelav** [comment]
oh yeah good point, I did forget one step in the installation process ! Will update ASAP

**Comment by Nitnelav** [comment]
all right, you can try with : 
https://github.com/Nitnelav/NoiseModelling-installer/releases/tag/v4.0.5

everything should work now. It will be updated in this repo shortly

**Comment by IsotoCedex** [comment]
Thank you so much!.
It works. I'm going to mess with the new modules and features.
Great job!

**Comment by gpetit** [comment]
Thanks to you for testing and for letting us know there was a bug !
