### ISSUE TITLE
NoiseModelling Not Starting on Windows 11

### ISSUE THREAD

**Issue by AlasdairGrant** [Universite-Gustave-Eiffel/NoiseModelling#611]
I have installed NoiseModelling from the Git Hub at the following link. It has installed the icon on the desktop but when I open it on a Windows 11 PC - it doesn't run. I dialogue box flashes but disappears. Just wondering if anyone knows of a way to resolve this.

**Comment by weiba388** [comment]
same problem, windows 11 PC.
you can try to run this file starup_windows.bat in the NoiseModelling_4.0.5/bin , it works for me.

**Comment by nicolas-f** [comment]
Hi,

It is the same issue as #610 
I've just replaced with the new exe created by @Nitnelav

**Comment by Nitnelav** [comment]
It stays a bit there on my machine too but it eventually proceeds to start GeoServer.
Maybe your anti malware / software scan is slowing things down ?
Try waiting to see how long it takes I guess.

**Comment by AlasdairGrant** [comment]
It stops after saying info etc maim started @24477ms

**Comment by AlasdairGrant** [comment]
This is what it looks like after five minutes: 

![image](https://github.com/Universite-Gustave-Eiffel/NoiseModelling/assets/30502638/973cf17e-7301-43ec-8d22-f752804a1c67)

**Comment by nicolas-f** [comment]
Hello,

As stated in https://noisemodelling.readthedocs.io/en/latest/Get_Started_GUI.html#step-2-start-noisemodelling-gui

If `main:Started` is displayed, this means that the application is ready and you can now open your browser. Be careful not to close this window, otherwise NoiseModelling will quit.
