### ISSUE TITLE
PK error

### ISSUE THREAD

**Issue by Donaldhermann** [Universite-Gustave-Eiffel/NoiseModelling#637]
Process failed during execution javax.script.ScriptException: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Violation d'index unique ou clé primaire: "PUBLIC.PRIMARY_KEY_9 ON PUBLIC.ROADS3(PK) VALUES ( /* 1 */ 1 )" Unique index or primary key violation: "PUBLIC.PRIMARY_KEY_9 ON PUBLIC.ROADS3(PK) VALUES ( /* 1 */ 1 )"; SQL statement: ALTER TABLE ROADS3 ADD PRIMARY KEY (PK) [23505-214] org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Violation d'index unique ou clé primaire: "PUBLIC.PRIMARY_KEY_9 ON PUBLIC.ROADS3(PK) VALUES ( /* 1 */ 1 )" Unique index or primary key violation: "PUBLIC.PRIMARY_KEY_9 ON PUBLIC.ROADS3(PK) VALUES ( /* 1 */ 1 )"; SQL statement: ALTER TABLE ROADS3 ADD PRIMARY KEY (PK) [23505-214] Violation d'index unique ou clé primaire: "PUBLIC.PRIMARY_KEY_9 ON PUBLIC.ROADS3(PK) VALUES ( /* 1 */ 1 )" Unique index or primary key violation: "PUBLIC.PRIMARY_KEY_9 ON PUBLIC.ROADS3(PK) VALUES ( /* 1 */ 1 )"; SQL statement: ALTER TABLE ROADS3 ADD PRIMARY KEY (PK) [23505-214]

**Comment by pierromond** [comment]
Hi ! It seems that your table ROADS3 have a PK column, but this column have repeated numbers which is not possible for a primary key column. Maybe try to remove this column before to generate it again. Or you can also add a new column called PK2 for example with the WPS block "add_primary_key".

**Comment by Donaldhermann** [comment]
Thx. It's good now!
