### ISSUE TITLE
Directivity calculation fails

### ISSUE THREAD

**Issue by berensc** [Universite-Gustave-Eiffel/NoiseModelling#652]
NoiseModelling 4.0.5 without GUI

**Describe the bug**
The calculation of the sound propagation of a directional siren (see example data in the attached zip) does not work.
Direction yaw=270 (southeast)
Height 40 m

Sample Data
[Data_to_Github.zip](https://github.com/Universite-Gustave-Eiffel/NoiseModelling/files/14649358/Data_to_Github.zip)

**To Reproduce**
1. Unzig the sample Data (attached Zip file) in a directory of your choise
2. Copy the **import_source_calc_noise._github.groovy** to the scriptrunner directory (ex. C:\NoiseModelling\scriptrunner_NM_4_0_5)
3. Change input paths in the import_source_calc_noise_github.groovy 
4. In the command prompt change the directiory to the scriptrunner (ex. cd C:\NoiseModelling\scriptrunner_NM_4_0_5)
5. run groovy script  .\bin\wps_scripts -w.\ -simport_source_calc_noise_github.groovy
6. See error message " NoiseModelling_Logfile.txt" 
7. Lday is not calculated correctly in the resulting Point-shape file source_lday.shp (LAEQ = 0)

**Expected behavior**
Like the results of the procedure with the tutorial data. 
[https://noisemodelling.readthedocs.io/en/latest/Noise_Map_From_Point_Source.html#step-5-bonus-change-the-directivity]

**Screenshots**
![image](https://github.com/Universite-Gustave-Eiffel/NoiseModelling/assets/113665244/9f8ad5b4-b361-4978-b013-47424dea8580)

**Additional context**

**Comment by nicolas-f** [comment]
Bonus you can generate a plot of your directivity with this code:

```groovy
        def htmlCode = runScript(connection, "noisemodelling/wps/NoiseModelling/PlotDirectivity.groovy",
          ["confDirId": 15, "tableSourceDirectivity": "Directivity"]);
        
        def htmlfile = new File('directivity.html')
	htmlfile.write(htmlCode)
```

![image](https://github.com/Universite-Gustave-Eiffel/NoiseModelling/assets/1382241/efed1181-e69e-4b17-ae92-fe2790a7f140)

**Comment by berensc** [comment]
Merci Nicolas

L’option «directivity » marche maintenant.
Mais les résultats ne sont pas cohérents avec la description du yaw dans la documentation.

***@***.***

Chez nous avec  yaw = 90 l’orientation de la source est ouest pas est et yaw =0 est sud et pas nord.

Tous les calcul avec la même  « directivity.csv »

Phi                       LW500
0-90                    0
90-270                -50
270-360              0
***@***.***

Mat beschten Gréiss.
Mit freundlichen Grüssen / Best regards / Salutations distinguées.

Carsten Berens
Dipl.-Ing. agr.
Gestionnaire système d’information géographique

Direction de la stratégie opérationnelle
Département planification
Service cartographie et analyses

Tél. +352 49771 2623
***@***.******@***.***>

[/Volumes/Accentaigu_Data/_CLIENTS/CGDIS/02601_corporate/Graphisme/Crea/01_logo/PRINCIPAL/PRINCIPAL/cgdis_logo_principal_RVB.jpg]

Corps grand-ducal d’incendie et de secours (CGDIS)
Centre National d’Incendie et de Secours - CNIS
3, boulevard de Kockelscheuer
L-1821 Luxembourg


Facebook<https://de-de.facebook.com/cgdis112/> Twitter<https://twitter.com/CGDISlux> Instagram<https://www.instagram.com/cgdislux/> YouTube<https://www.youtube.com/channel/UCnlgFPDkPktnS0z5OEZjiWQ>

www.cgdis.lu<http://www.cgdis.lu/> – www.112.lu<http://www.112.lu/>

**Comment by nicolas-f** [comment]
> Merci Nicolas L’option «directivity » marche maintenant. Mais les résultats ne sont pas cohérents avec la description du yaw dans la documentation. ***@***.*** Chez nous avec yaw = 90 l’orientation de la source est ouest pas est et yaw =0 est sud et pas nord. Tous les calcul avec la même « directivity.csv » Phi LW500 0-90 0 90-270 -50 270-360 0 ***@***.*** 

D’après les graphique de la source, elle émet à l'arrière et non à l'avant, c'est peut être pour ça.

**Comment by berensc** [comment]
Salut Nicolas
C'est tout à fait exact. J'ai utilisé le faux "directivity.csv " Ici le bon fichier.
[Directivity.csv](https://github.com/Universite-Gustave-Eiffel/NoiseModelling/files/14665303/Directivity.csv)
