### ISSUE TITLE
Null data for a large proportion of receivers

### ISSUE THREAD

**Issue by annalisasheehan** [Universite-Gustave-Eiffel/NoiseModelling#654]
If you ignore this issue template, we may not be able to answer your issue.

**NoiseModelling version**
NoiseModelling 4.0.5/scriptrunner 4.0.5. 

**Describe the bug**
I am running Noise_level_from_source for a set of receivers, using major roads in a city as my source with a max source-receiver distance of 1km. For a large proportion of my receivers the output is providing LAEQ=-92.01 and LEQ=-89.97. 

The receivers with missing data (LAEQ=-92.01 and LEQ=-89.97) is the same regardless of if I set the max source-receiver distance to 1km, 2km or 5km. All my receivers are within 1km of a major road and therefore should have noise estimates. I was wondering whether the splitting of the data into Cells which are created for parallelization may be causing this? How does the size of the cell get determined? Does the cell location vary by receiver or is this a static 'cookie cut' of data across the entire data set before processing? If a receiver lies on the border of a cell will data from neighbouring cell be used to estimate noise? 

**To Reproduce**

I am pasting my script runner bash script here with shortened file names, however, I follow the same steps in the GUI. 

#! /bin/bash

# Step 1: Upload files to database
# create (or load existing) database and load a shape file into the database
./bin/wps_scripts -w ./ -s noisemodelling/wps/Import_and_Export/Import_File.groovy -pathFile "~/CORINE_BCN_G_Clean.shp" -inputSRID 25831 -tableName GROUND_TYPE
./bin/wps_scripts -w ./ -s noisemodelling/wps/Import_and_Export/Import_File.groovy -pathFile "~/Buildings_height.shp" -inputSRID 25831 -tableName BUILDINGS
./bin/wps_scripts -w ./ -s noisemodelling/wps/Import_and_Export/Import_File.groovy -pathFile "~/receivers.shp" -inputSRID 25831 -tableName RECEIVERS
./bin/wps_scripts -w ./ -s noisemodelling/wps/Import_and_Export/Import_File.groovy -pathFile "~/Major_roads_noise_model.shp" -inputSRID 25831 -tableName ROADS

# Step 2: Calculate road emission road map from traffic flow/speed estimates
./bin/wps_scripts -w ./ -s noisemodelling/wps/NoiseModelling/Road_Emission_from_Traffic.groovy -tableRoads ROADS

# Step 5: Run Calculation
./bin/wps_scripts -w ./ -s noisemodelling/wps/NoiseModelling/Noise_level_from_source.groovy -tableBuilding BUILDINGS -tableSources LW_ROADS -tableReceivers RECEIVERS -tableGroundAbs GROUND_TYPE -confMaxSrcDist 2000

# Step 6: Export (& see) the results
./bin/wps_scripts -w ./ -s noisemodelling/wps/Import_and_Export/Export_Table.groovy -exportPath "~/LDAY_GEOM.shp" -tableToExport LDAY_GEOM
./bin/wps_scripts -w ./ -s noisemodelling/wps/Import_and_Export/Export_Table.groovy -exportPath "~/LDEN_GEOM.shp" -tableToExport LDEN_GEOM
./bin/wps_scripts -w ./ -s noisemodelling/wps/Import_and_Export/Export_Table.groovy -exportPath "~/LEVENING_GEOM.shp" -tableToExport LEVENING_GEOM
./bin/wps_scripts -w ./ -s noisemodelling/wps/Import_and_Export/Export_Table.groovy -exportPath "~/LNIGHT_GEOM.shp" -tableToExport LNIGHT_GEOM

**Geoserver log**

Attach geoserver log located in **data_dir\logs\geoserver.log**

**Expected behavior**
Estimated noise for all receivers which are within the max source-receiver distance from the road. 
**Screenshots**

**Additional context**

**Comment by nicolas-f** [comment]
Hi,

Sorry but there is too little information to help you.

You should provide a test case with the data.

**Comment by pierromond** [comment]
./bin/wps_scripts -w ./ -s noisemodelling/wps/NoiseModelling/Noise_level_from_source.groovy -tableBuilding BUILDINGS -tableSources LW_ROADS -tableReceivers RECEIVERS -tableGroundAbs GROUND_TYPE -confMaxSrcDist 2000

It seems that you don't activate horizontal or vertical diffraction... In this case, buildings have infinite heights, for example, so you can see what you're talking about... but yes, a test case will be needed to more precise answer.
