### ISSUE TITLE
How to test a new WPS block?

### ISSUE THREAD

**Issue by SamuelMarsault** [Universite-Gustave-Eiffel/NoiseModelling#664]
**Is your feature request related to a problem ? Please describe.**

Hello, everyone ! I have a brief question. I created a WPS block that uses geoclimate to get us files with information about a municipality (for example by putting Paris). Locally, when I run it (so without geoserver and lib that are only used in noise modeling), it works. However, I would like to see if this also works on noiseModelling. How could I do that ?

**Comment by nicolas-f** [comment]
Hello,

There is a guide here:

https://noisemodelling.readthedocs.io/en/latest/Own_Wps.html
