### ISSUE TITLE
NOISE MODELLING

### ISSUE THREAD

**Issue by Alba344** [Universite-Gustave-Eiffel/NoiseModelling#667]
I am a student of the University of Extremadura (Polytechnic School) I am doing a final degree work using Noise Modelling and QGIS tools. I am doing it on the city of Cáceres and I am having some problems and I would like to solve them. I have followed perfectly the tutorial and in that case I have the expected results, but I don't know if I should change the values of PK and OSM_ID so that they correspond with the town of Caceres and its streets. I have set the EPSG that corresponds to Cáceres, it is 25829. 

Where do I get the map to process the data and be able to modify it in QGIS for specific streets in Cáceres? I don't get the streets I want by changing the OSM_ID. Any ideas?

**Comment by pierromond** [comment]
Dear Alba, 

I am not sure to really understand your issue.

FYI we have a just realeased new tutorial that could also interest you : https://github.com/SamuelMarsault/noiseModelling_OSM_Tool

Please give us more info.

Kind regards.

**Comment by MaguetteD** [comment]
To get maps of specific streets in Cáceres in QGIS, use data sources like OSM via tools like Overpass Turbo or Geofabrik. If the desired streets are not found by OSM_ID, try identifying them with other attributes such as **'name'** or **'highway'**. Make sure you have more precise geographical information.
