### ISSUE TITLE
Issue when Running Noise_Level_From_Source. (Process failed during execution javax.script.ScriptException: java.lang.IllegalArgumentException: Invalid ordinate index: 2 java.lang.IllegalArgumentException: Invalid ordinate index: 2 Invalid ordinate index: 2)

### ISSUE THREAD

**Issue by LontongBalado** [Universite-Gustave-Eiffel/NoiseModelling#671]
**NoiseModelling version**
Noise Modelling Versioin 4.0.5 with GUI

**Describe the bug**
When I'm using Noise_level_from_source, The program wouldn't want to execute and give the message in the console log.

"Process failed during execution javax.script.ScriptException: java.lang.IllegalArgumentException: Invalid ordinate index: 2 java.lang.IllegalArgumentException: Invalid ordinate index: 2 Invalid ordinate index: 2"

I recently know that the Geometry is 2D and not 3D, but I don't know how to change it.

**Geoserver log**

Attach geoserver log located in **data_dir\logs\geoserver.log**

Request: execute
    service = WPS
    version = 1.0.0
    baseUrl = http://127.0.0.1:9580/geoserver/
    identifier:
        value = NoiseModelling:Noise_level_from_source
    dataInputs:
        input[0]:
            identifier = net.opengis.ows11.impl.CodeTypeImpl@272be087 (value: tableSources, codeSpace: null)
            data = net.opengis.wps10.impl.DataTypeImpl@22bca7e3input[0]:
            identifier = net.opengis.ows11.impl.CodeTypeImpl@6b0b70e6 (value: tableReceivers, codeSpace: null)
            data = net.opengis.wps10.impl.DataTypeImpl@31fe7ee0input[0]:
            identifier = net.opengis.ows11.impl.CodeTypeImpl@49298f80 (value: tableBuilding, codeSpace: null)
            data = net.opengis.wps10.impl.DataTypeImpl@e6daaf9
    responseForm:
        rawDataOutput:
            identifier = net.opengis.ows11.impl.CodeTypeImpl@3e516792 (value: result, codeSpace: null)

**Expected behavior**
I'm Expected the function to did all the same as shown in documentation because I already follow all the steps correctly as far as I know.

link to the documentation : https://noisemodelling.readthedocs.io/en/latest/Noise_Map_From_Point_Source.html

**Additional context**
I'm using QGIS 3.38, and I'm a beginner. Any help would be resourceful for me.

Kind Regards

Nayandra Hasan Sudra

**Comment by LontongBalado** [comment]
I forgot to put the Receivers table 

![image_2024-07-02_194646000](https://github.com/Universite-Gustave-Eiffel/NoiseModelling/assets/174445905/6c380160-649d-421f-8c43-3ef03da69d46)

Thank you in advance

**Comment by MaguetteD** [comment]
Hi, you need to apply the Set_Height script to both receivers and sources.
Can i see your source table please, thanks.

**Comment by LontongBalado** [comment]
> Hi, you need to apply the Set_Height script to both receivers and sources. Can i see your source table please, thanks.

Hi, it's solved now. Your input is really useful. Thank you
