### ISSUE TITLE
3d visualization

### ISSUE THREAD

**Issue by LontongBalado** [Universite-Gustave-Eiffel/NoiseModelling#672]
Is it possible to visualize calculation in 3D with Qgis ? if it possible, is there any tutorials ?

**Comment by nicolas-f** [comment]
Hello,

Qgis i don't know, but google earth yes.

You can use the following parameter before running your calculation (will increase the computation time significantly)

Noise_level_from_source
confRaysName=file:///C:/dir/map.kml

The open the kml files on google earth desktop or web ([https://earth.google.com](https://earth.google.com))

https://github.com/Universite-Gustave-Eiffel/NoiseModelling/blob/v4.0.5/wps_scripts/src/main/groovy/org/noise_planet/noisemodelling/wps/NoiseModelling/Noise_level_from_source.groovy#L274

This parameter is not in the documentation/tutorials

**Comment by LontongBalado** [comment]
> Hello,
> 
> Qgis i don't know, but google earth yes.
> 
> You can use the following parameter before running your calculation (will increase the computation time significantly)
> 
> Noise_level_from_source confRaysName=file:///C:/dir/map.kml
> 
> The open the kml files on google earth desktop or web (https://earth.google.com)
> 
> https://github.com/Universite-Gustave-Eiffel/NoiseModelling/blob/v4.0.5/wps_scripts/src/main/groovy/org/noise_planet/noisemodelling/wps/NoiseModelling/Noise_level_from_source.groovy#L274
> 
> This parameter is not in the documentation/tutorials

That's all right, I will try it first. Thank you
